# Generated by Django 5.0.1 on 2024-01-29 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('title_rank', models.SmallIntegerField(choices=[(1, 'Professor'), (2, 'Assistant Professor'), (3, 'Lecturer'), (4, 'Assistant Lecturer')], default=4)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('cv_link', models.URLField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=155)),
                ('description', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('poster', models.CharField(blank=True, max_length=255)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lecturer')),
            ],
        ),
    ]
