# Generated by Django 5.0.1 on 2024-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
