# Generated by Django 5.0.1 on 2024-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='cv_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
