# Generated by Django 5.0.1 on 2024-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('student_type', models.CharField(choices=[('ST', 'Student'), ('EM', 'Employer'), ('OT', 'Others')], default='OT', max_length=2)),
                ('courses', models.ManyToManyField(to='core.course')),
            ],
        ),
    ]
