# Generated by Django 5.0.1 on 2024-05-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enroller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enroller',
            new_name='Studnet',
        ),
    ]
