# Generated by Django 5.0.1 on 2024-05-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_enroller_studnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnet',
            new_name='Student',
        ),
    ]
