# Generated by Django 5.0.1 on 2024-05-03 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_studnet_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
