# Generated by Django 5.0.1 on 2024-05-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='poster',
        ),
    ]
